### ISSUE TITLE
Unsubscribe from forum email notifications may not work

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1474] opened 2016-09-10 11:28 UTC
User complains that email notifications are still being sent even after unsubscribing.

**Comment by weiqingtoh** [comment] 2017-02-24 07:48
Did some quick investigation and outcome is to close this because: (i) it seems to be fixed (the PR which fixes this did not link to this issue), and (ii) there is not enough information to reproduce this. 

Findings:
 - When a post is created in a topic, mailer is sent to subscribers of that topic.
 - When a topic is created in a forum, mailer is sent to subscribers of that forum. 
 - Both the subscribe and unsubscribe buttons for both the forum and topics both work. I've tried toggling both multiple times to ensure this subscriptions for both objects are updated.

**Closed by weiqingtoh** 2017-02-24 07:48 UTC
Labels: bug, Current sprint
