### ISSUE TITLE
Need an easy way for the instructor to publish/unpublish assignments from overview list.

### ISSUE THREAD

**Issue by benleong** [Coursemology/coursemology2#1538] opened 2016-09-28 09:13 UTC
Example is this page: https://beta.coursemology.org/courses/4/assessments?category=6&tab=14.

**Comment by benleong** [comment] 2016-09-28 09:14
Current workflow to publish assignments is really annoying.

**Comment by weiqingtoh** [comment] 2018-06-22 06:13
Duplicate of issue 1558

**Closed** 2018-06-22 06:12 UTC
Labels: UI, enhancement
