### ISSUE TITLE
Line numbers don't align with code

### ISSUE THREAD

**Issue by hongshaoyang** [Coursemology/coursemology2#3137] opened 2018-10-07 15:46 UTC
minor UI issue. sometimes, when on different zooms on chrome, the line numbers don't align up with the code.

See the following screenshots:

![image](https://user-images.githubusercontent.com/19281800/46583518-36980f00-ca8b-11e8-947b-927a23e026de.png)

![image](https://user-images.githubusercontent.com/19281800/46583510-21bb7b80-ca8b-11e8-91e6-c9177ef99f55.png)

**Comment by jeremyyap** [comment] 2018-10-07 15:47
Duplicate of #2480

**Closed by jeremyyap** 2018-10-07 15:47 UTC
