### ISSUE TITLE
Annotation box collapses when clicking on the textarea and edit button on md and below 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Coursemology/coursemology2#2796] opened 2018-01-30 04:30 UTC
To reproduce

1. Open any student mission or code which allows annotations 
2. Narrow the browser window down to md, when the annotation column becomes inline (instead of appearing in a separate column on the left like in lg and above) 
3. Click on the [+] button to add an annotation 
4. Click on the textarea with 'Enter your comment here' placeholder text 
5. The annotation box collapses when the mouse is released, instead of the textarea being focused as the user would expect 

It seems that the event is bubbling up, which causes it to be captured by the parent event handler which then closes the annotation box. The same happens if you try to edit an existing annotation. 

This does not happen in lg and above, when the annotation appears on the left of the code instead of on top of it. 

Reproduced on Firefox 59b4 and Chrome 64.

**Comment by weiqingtoh** [comment] 2018-02-27 09:47
Duplicate of #2840. 

![comments-bug](https://user-images.githubusercontent.com/4353853/36360963-5cbc5ed0-1563-11e8-87cd-5ddcf1762a53.gif)

**Closed** 2018-03-06 09:48 UTC
Labels: Groomed, UI, bug
