### ISSUE TITLE
request to be instructor > pressed edit request > error

### ISSUE THREAD

**Issue by yshmarov** [Coursemology/coursemology2#3796] opened 2020-06-14 15:28 UTC
![image](https://user-images.githubusercontent.com/13472945/84597473-7cae9400-ae64-11ea-9cc4-484e0768b97e.png)

**Comment by ekowidianto** [comment] 2021-09-07 09:14
Unable to reproduce the bug and will only get this page if someone tries to access a role request other than theirs. I will close this issue as of now and can be re-opened when it happens again in the future.

**Closed by ekowidianto** 2021-09-07 09:14 UTC
Labels: bug
