### ISSUE TITLE
Show MCQ/MRQ options when viewing the assessment

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1952] opened 2017-01-24 06:47 UTC
When editing the assessment, the question cards do not show the options.

Options give context for the questions and it's useful to see them without having to click into the question.

**Comment by jeremyyap** [comment] 2017-02-26 03:07
Duplicate of #1546?

**Comment by weiqingtoh** [comment] 2017-02-26 10:34
Yup this is a duplicate.

**Closed** 2017-02-26 10:46 UTC
Labels: UI
