### ISSUE TITLE
Static attempt link

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1957] opened 2017-01-25 08:09 UTC
Used for submissions for video and assessments. To also implement for surveys if required.

**Comment by fonglh** [comment] 2017-01-25 08:27
This means the URL for attempt is always the same, but is redirected to an existing submission/video/survey if it exists, or else it creates a new one and redirects the user there?

**Comment by weiqingtoh** [comment] 2017-01-25 10:55
Yup - this helps if we need to do some copy pasting!

**Comment by kxmbrian** [comment] 2017-04-24 11:26
The static link for surveys is `courses/:course_id/surveys/:survey_id`. Users can access the edit page to respond to the survey from there. (#2237)

**Comment by kxmbrian** [comment] 2017-04-24 11:27
Duplicate of #1737

**Closed by kxmbrian** 2017-04-24 11:27 UTC
Labels: enhancement, Tech review discussion
