### ISSUE TITLE
Line numbers do not align with code in zoom mode

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#2480] opened 2017-08-31 04:11 UTC
For long code pieces, the line number and code could get misaligned when zooming.

![unnamed](https://user-images.githubusercontent.com/4983239/29906070-10c26100-8e45-11e7-93c3-88acc75ff545.png)

**Comment by hongshaoyang** [comment] 2018-10-07 15:49
might changing the font on the line numbers to match the code work?

**Comment by jeremyyap** [comment] 2018-10-07 16:00
We don't really have the capacity to look into this issue right now, but pull requests are always welcome!

**Comment by cysjonathan** [comment] 2020-06-29 18:22
I believe a quick fix for this is to add `height: 20` into `editorLineNumber` and `editorLineNumberWithComments`

You can view the 4 location that need changes here:

https://github.com/Coursemology/coursemology2/blob/50680a72a1078a9b68b729f3f0803cb17c5ca411/client/app/bundles/course/assessment/submission/components/ReadOnlyEditor/NarrowEditor.jsx#L28

https://github.com/Coursemology/coursemology2/blob/50680a72a1078a9b68b729f3f0803cb17c5ca411/client/app/bundles/course/assessment/submission/components/ReadOnlyEditor/NarrowEditor.jsx#L37

https://github.com/Coursemology/coursemology2/blob/8d50d26ea8b554cc9fc24a91c913a730e52c7eb6/client/app/bundles/course/assessment/submission/components/ReadOnlyEditor/WideEditor.jsx#L36

https://github.com/Coursemology/coursemology2/blob/8d50d26ea8b554cc9fc24a91c913a730e52c7eb6/client/app/bundles/course/assessment/submission/components/ReadOnlyEditor/WideEditor.jsx#L45

Can someone implement, test and deploy the fix?
https://coursemology.org/courses/1875/assessments/36226/submissions/917862/edit
Example of misalignment when there are many lines of code. It is very unusable.

**Comment by cysjonathan** [comment] 2021-10-31 11:07
Seems to have issues in Chrome, mac for submissions with many lines.
![image](https://user-images.githubusercontent.com/10083037/139579917-650b881d-6a2e-4acd-87b9-1065a73bdbba.png)
Cannot reproduce on windows.

**Closed** 2021-11-06 17:10 UTC
Labels: bug
