### ISSUE TITLE
Fail to evaluate C++ code 

### ISSUE THREAD

**Issue by dezhanglee** [Coursemology/coursemology2#3557] opened 2019-06-09 14:40 UTC
Related to #3552 , same error message generated
https://coursemology.org/courses/1710/assessments/29332/submissions/748487/edit

This person (but I think he changed his prev submission, so cant see the error now). We raised the time and memory to max, but still same error

**Comment by fonglh** [comment] 2019-06-10 06:21
You can follow the instructions at https://github.com/coursemology/evaluator-images#using-the-images-for-debugging to debug on your own machine.

See https://docs.docker.com/config/containers/resource_constraints/ for how to set memory limits. You can see https://github.com/Coursemology/coursemology2/issues/3552#issuecomment-500304151 for the memory and time limits imposed by Coursemology.

**Comment by trangmei** [comment] 2019-09-13 22:59
Cpp autograder reliability issue is no longer observed after more memory is allocated to worker servers.

**Comment by leongwaikay** [comment] 2021-10-30 08:38
Issue is still existing. Please reopen and fix it properly and not just allocate more memory. Eventually we will end up just increasing and increasing the memory over time.

**Comment by benleong** [comment] 2021-10-30 08:44
I think the problem is that we don't know the root cause. >_<

**Comment by cysjonathan** [comment] 2021-10-30 09:11
To identify and fix
[ ] Why package cannot be updated https://coursemology.org/courses/2107/assessments/46292/question/programming/120897/edit
[ ] Why autograder containers fail randomly

Logs during package update
```
cat tests/prepend.cc submission/template.c tests/append.cc tests/autograde.cc > answer.cc
g++ -isystem /home/coursemology/googletest/googletest/include -g -w -Wall -Wextra -pthread -std=c++11 answer.cc /home/coursemology/googletest/googletest/libgtest.a -o answer.bin
Makefile:21: recipe for target 'answer.bin' failed
```

**Comment by cysjonathan** [comment] 2021-11-21 10:16
After investigation into the memory issue and related C++ failure issues #3552 #3640 #3648
[The fix of adjusting time/memory limits in Coursemology question interface](https://github.com/Coursemology/coursemology2/issues/3552#issuecomment-499316468) triggers a re-evaluation of the answers, which may or may not result in a successful evaluation.

The root cause of the evaluation failure that generates this std error message is due to insufficient memory.
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
make: *** [answer.bin] Error 4
```

The C++ compile step for questions in the [TIC1001 module](https://coursemology.org/courses/2107/) generally takes ~100-180MB of memory, and which explains why reducing memory to only 128MB memory + 0 swap in #3640 causes C++ autograder to fail consistently due to insufficient memory. Instating 128MB swap in #3648 somewhat relieves this problem. However, we now observe that the autograder fails __randomly__.

A similar issue was observed in an article, extract below:
> When we reintroduced and increased swap memory for the Docker containers, the issue with simple shell commands running out of memory disappeared. But only for a while. It came back and even containers with `--memory=1024m` started to fail occasionally (and they use another 1 GB of swap).

&mdash; https://500.keboola.com/cp-in-docker-cannot-allocate-memory-part-2-369490f1a88f

It seems that the problem lies in the use of swap memory and how linux does disk-caching. Because the machine does not write to disk fast enough, the cache risks corruption or out of memory.

#4188 has increased memory limit to 1024MB and removed swap, which should 
1. Increase evaluation speed (reduce evaluation time, since no need to use swap)
2. Avoid random failures

At the same time, in case we ever need to re-instate non-zero swap values, I have adjusted worker vm configurations from `vm.dirty_background_ratio = 10` and `vm.dirty_ratio = 20` to
```sudo sysctl -w vm.dirty_background_bytes=33554432 # 32MB
sudo sysctl -w vm.dirty_bytes=536870912 # 512MB
sysctl -p```

I did not observe any C++ autograder failures due to `g++: internal compiler error: Killed` while monitoring the VMs over the past 2 days, so will be closing this for now.

Other resources on vm-dirty values
https://lonesysadmin.net/2013/12/22/better-linux-disk-caching-performance-vm-dirty_ratio/
https://blog.titanwolf.in/a?ID=01400-54e1bb07-f6aa-4014-b59b-c418c8316703

**Closed by cysjonathan** 2021-11-21 10:16 UTC
Labels: bug
